from .AccountSerializer import AccountSerilizer
from .DoctorAccountSerializer import DoctorAccountSerializer, ViewDoctorDetails, UpdateDoctorAccountSerializer, UpdateDoctorProfilePicSerializer, UpdateDoctorPasswordSerializer, DoctorDashboardDetailsSerializer
from .PatientAccountSerializer import PatientAccountSerializer, PatientProfileSerializer, PatientDashboardSerializer, PatientMedicalInfoSerializer, UpdatePatientAccountSerializer, UpdatePatientPasswordSerializer, UpdatePatientProfilePicSerializer
from .LoginSerializer import LoginSerializer
from .AppointmentSerializer import AppointmentSerializer, BookAppointmentSerializer, ViewAppointmentListSerializer, UpdateAppointmentSerializer
from .MedicalRecordSerializer import MedicalRecordSerializer, CreateMedicalRecordSerializer
from .FeedbackSerializer import FeedbackSerializer, CreateFeedbackSerializer
