# Generated by Django 3.0.6 on 2020-08-27 04:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Ear, nose and throat (ENT)', 'Ear, nose and throat (ENT)'), ('Dental', 'Dental'), ('Ophthalmology', 'Ophthalmology'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('Nutrition and Dietics', 'Nutrition and Dietics')], max_length=100)),
                ('specialization', models.CharField(max_length=300)),
                ('doctor_first_name', models.CharField(max_length=100)),
                ('doctor_last_name', models.CharField(max_length=100)),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(12.0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(700.0)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=6)),
                ('dob', models.DateField()),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Ear, nose and throat (ENT)', 'Ear, nose and throat (ENT)'), ('Dental', 'Dental'), ('Ophthalmology', 'Ophthalmology'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('Nutrition and Dietics', 'Nutrition and Dietics')], max_length=100)),
                ('specialization', models.CharField(max_length=300)),
                ('registration_number', models.IntegerField(default=0)),
                ('years_of_experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('hospital_address', models.CharField(blank=True, max_length=300)),
                ('start_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('start_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('end_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('end_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('nationality', models.CharField(choices=[('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Bangladeshi', 'Bangladeshi'), ('Belgian', 'Belgian'), ('Bolivian', 'Bolivian'), ('Batswana', 'Batswana'), ('Brazilian', 'Brazilian'), ('Bulgarian', 'Bulgarian'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Colombian', 'Colombian'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dominican', 'Dominican'), ('Ecuadorian', 'Ecuadorian'), ('Egyptian', 'Egyptian'), ('Salvadorian', 'Salvadorian'), ('English', 'English'), ('Estonian', 'Estonian'), ('Ethiopian', 'Ethiopian'), ('Fijian', 'Fijian'), ('Finnish', 'Finnish'), ('French', 'French'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Guatemalan', 'Guatemalan'), ('Haitian', 'Haitian'), ('Honduran', 'Honduran'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kenyan', 'Kenyan'), ('Kuwaiti', 'Kuwaiti'), ('Lao', 'Lao'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Libyan', 'Libyan'), ('Lithuanian', 'Lithuanian'), ('Malagasy', 'Malagasy'), ('Malaysian', 'Malaysian'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Mexican', 'Mexican'), ('Mongolian', 'Mongolian'), ('Moroccan', 'Moroccan'), ('Mozambican', 'Mozambican'), ('Namibian', 'Namibian'), ('Nepalese', 'Nepalese'), ('Dutch', 'Dutch'), ('New Zealand', 'New Zealand'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Norwegian', 'Norwegian'), ('Pakistani', 'Pakistani'), ('Panamanian', 'Panamanian'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Philippine', 'Philippine'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Saudi', 'Saudi'), ('Scottish', 'Scottish'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Singaporean', 'Singaporean'), ('Slovak', 'Slovak'), ('South African', 'South African'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('Sudanese', 'Sudanese'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajikistani', 'Tajikistani'), ('Thai', 'Thai'), ('Tongan', 'Tongan'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Ukrainian', 'Ukrainian'), ('Emirati', 'Emirati'), ('British', 'British'), ('American', 'American'), ('Uruguayan', 'Uruguayan'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], max_length=50)),
                ('home_address', models.CharField(max_length=300)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/doctor/profile')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=6)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('nationality', models.CharField(choices=[('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Bangladeshi', 'Bangladeshi'), ('Belgian', 'Belgian'), ('Bolivian', 'Bolivian'), ('Batswana', 'Batswana'), ('Brazilian', 'Brazilian'), ('Bulgarian', 'Bulgarian'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Colombian', 'Colombian'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dominican', 'Dominican'), ('Ecuadorian', 'Ecuadorian'), ('Egyptian', 'Egyptian'), ('Salvadorian', 'Salvadorian'), ('English', 'English'), ('Estonian', 'Estonian'), ('Ethiopian', 'Ethiopian'), ('Fijian', 'Fijian'), ('Finnish', 'Finnish'), ('French', 'French'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Guatemalan', 'Guatemalan'), ('Haitian', 'Haitian'), ('Honduran', 'Honduran'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kenyan', 'Kenyan'), ('Kuwaiti', 'Kuwaiti'), ('Lao', 'Lao'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Libyan', 'Libyan'), ('Lithuanian', 'Lithuanian'), ('Malagasy', 'Malagasy'), ('Malaysian', 'Malaysian'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Mexican', 'Mexican'), ('Mongolian', 'Mongolian'), ('Moroccan', 'Moroccan'), ('Mozambican', 'Mozambican'), ('Namibian', 'Namibian'), ('Nepalese', 'Nepalese'), ('Dutch', 'Dutch'), ('New Zealand', 'New Zealand'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Norwegian', 'Norwegian'), ('Pakistani', 'Pakistani'), ('Panamanian', 'Panamanian'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Philippine', 'Philippine'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Saudi', 'Saudi'), ('Scottish', 'Scottish'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Singaporean', 'Singaporean'), ('Slovak', 'Slovak'), ('South African', 'South African'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('Sudanese', 'Sudanese'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajikistani', 'Tajikistani'), ('Thai', 'Thai'), ('Tongan', 'Tongan'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Ukrainian', 'Ukrainian'), ('Emirati', 'Emirati'), ('British', 'British'), ('American', 'American'), ('Uruguayan', 'Uruguayan'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], max_length=50)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(12.0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(700.0)])),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('home_address', models.CharField(max_length=300)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile')),
                ('pre_medical_conditions', models.CharField(max_length=300)),
                ('surgeries_in_past', models.CharField(max_length=300)),
                ('alergies', models.CharField(max_length=300)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Ear, nose and throat (ENT)', 'Ear, nose and throat (ENT)'), ('Dental', 'Dental'), ('Ophthalmology', 'Ophthalmology'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('Nutrition and Dietics', 'Nutrition and Dietics')], max_length=100)),
                ('specialization', models.CharField(max_length=300)),
                ('doctor_first_name', models.CharField(max_length=100)),
                ('doctor_last_name', models.CharField(max_length=100)),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(12.0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(700.0)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('date', models.DateField()),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('diagnosis', models.CharField(max_length=200)),
                ('medical_treatment', models.CharField(max_length=200)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DoctorAccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PatientAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DoctorAccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PatientAccount')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DoctorAccount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PatientAccount'),
        ),
    ]
